export const ORDER_CREATE_REQUEST = 'OREDER_CREATE_REQUEST'
export const ORDER_CREATE_FAIL = 'OREDER_CREATE_FAIL'
export const ORDER_CREATE_SUCCESS = 'OREDER_CREATE_SUCCESS'
export const ORDER_CREATE_RESET = 'OREDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'OREDER_DETAILS_REQUEST'
export const ORDER_DETAILS_FAIL = 'OREDER_DETAILS_FAIL'
export const ORDER_DETAILS_SUCCESS = 'OREDER_DETAILS_SUCCESS'

export const ORDER_PAY_REQUEST = 'OREDER_PAY_REQUEST'
export const ORDER_PAY_FAIL = 'OREDER_PAY_FAIL'
export const ORDER_PAY_SUCCESS = 'OREDER_PAY_SUCCESS'
export const ORDER_PAY_RESET = 'OREDER_PAY_RESET'

export const ORDER_MYORDERS_REQUEST = 'OREDER_MYORDERS_REQUEST'
export const ORDER_MYORDERS_FAIL = 'OREDER_MYORDERS_FAIL'
export const ORDER_MYORDERS_SUCCESS = 'OREDER_MYORDERS_SUCCESS'
export const ORDER_MYORDERS_RESET = 'OREDER_MYORDERS_RESET'
